#!/usr/bin/env bash
# Syncs the vendored agent tools from upstream and records the exact commits in tooling/vendor.lock.
# Run from anywhere: bash tooling/sync-vendor.sh. Needs git, rsync and an authenticated gh.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
lock="$root/tooling/vendor.lock"
work="$(mktemp -d)"   # upstream checkouts; the OS clears the temp folder

# destination | upstream repository | ref ("latest-release" or a branch) | path inside upstream
entries=(
  "skills/ponytail|DietrichGebert/ponytail|latest-release|skills/ponytail"
  "plugins/pstack|cursor/plugins|main|pstack"
  "plugins/thermos|cursor/plugins|main|thermos"
)

{
  printf '# Generated by tooling/sync-vendor.sh. Do not edit by hand.\n'
  printf '# destination upstream ref commit\n'
} > "$lock.tmp"

for entry in "${entries[@]}"; do
  IFS='|' read -r dest repo ref path <<< "$entry"
  if [[ "$ref" == latest-release ]]; then
    ref="$(gh api "repos/$repo/releases/latest" --jq .tag_name)"
  fi
  checkout="$work/${repo//\//_}@$ref"
  if [[ ! -d "$checkout" ]]; then
    git -c advice.detachedHead=false clone -q --depth 1 --branch "$ref" "https://github.com/$repo.git" "$checkout"
  fi
  if [[ ! -d "$checkout/$path" ]]; then
    printf 'sync-vendor: %s has no %s at %s\n' "$repo" "$path" "$ref" >&2
    exit 1
  fi
  mkdir -p "$root/$dest"
  rsync -a --delete --exclude .git "$checkout/$path/" "$root/$dest/"
  # Keep the upstream license next to the copy when the subfolder has none of its own.
  [[ -f "$root/$dest/LICENSE" ]] || cp "$checkout/LICENSE" "$root/$dest/LICENSE"
  printf '%s %s %s %s\n' "$dest" "$repo" "$ref" "$(git -C "$checkout" rev-parse HEAD)" >> "$lock.tmp"
done

mv "$lock.tmp" "$lock"
cat "$lock"
